language: objective-c
before_install:
  - brew update
  - brew outdated xctool || brew upgrade xctool
script:
  - xctool -workspace WhereRU.xcworkspace -scheme WhereRU -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xctool test -workspace WhereRU.xcworkspace -scheme WhereRUTests -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
