source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'
pod 'Reachability', '~> 3.1.1'
pod 'Mantle', '~> 1.3.1'
pod 'TSMessages', '~> 0.9.4'
pod 'SVProgressHUD', '~> 1.0'
pod 'SVPullToRefresh', '~> 0.4.1'
pod 'JSONKit-NoWarning', '~> 1.2'
#pod 'SDWebImage', '~>3.6'
#pod 'UIActivityIndicator-for-SDWebImage', '~> 1.0.5'
pod 'AFNetworking', '~> 2.3.1'
#pod 'ICViewPager', '~> 1.5.1'
pod 'RSKImageCropper'
pod 'JASwipeCell'
pod 'PureLayout', '~> 2.0.1'