#source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'
pod 'Reachability', '~> 3.1.1'
#pod 'Mantle', '~> 1.3.1'
pod 'TSMessages', '~> 0.9.4'
pod 'SVProgressHUD', '~> 1.0'
pod 'SVPullToRefresh', '~> 0.4.1'
pod 'JSONKit-NoWarning', '~> 1.2'
pod 'SDWebImage', '~>3.7.1'
pod 'UIActivityIndicator-for-SDWebImage', '~> 1.2'
pod 'AFNetworking', '~> 2.3.1'
#pod 'ICViewPager', '~> 1.5.1'
pod 'RSKImageCropper', '~>0.3.0'
#pod 'JASwipeCell'
#pod 'PureLayout', '~> 2.0.1'
#pod 'DAContextMenuTableViewController'
pod 'SWTableViewCell', '~> 0.3.6'
pod 'IQKeyboardManager'

pod 'AMap2DMap'
pod 'AMapSearch'
