#source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
pod 'Reachability', '~> 3.1.1'
#pod 'Mantle', '~> 1.3.1'
pod 'TSMessages', '~> 0.9.4'
pod 'SVProgressHUD', '~> 1.0'
#pod 'SVPullToRefresh', '~> 0.4.1'
pod 'MJRefresh', '~> 1.4.5'
#pod 'JSONKit-NoWarning', '~> 1.2'
pod 'SDWebImage', '~>3.7.1'
pod 'UIActivityIndicator-for-SDWebImage', '~> 1.2'
#pod 'AFNetworking', '~> 2.3.1'
#pod 'ICViewPager', '~> 1.5.1'
pod 'RSKImageCropper', '~>1.1.3'
#pod 'JASwipeCell'
#pod 'PureLayout', '~> 2.0.1'
#pod 'DAContextMenuTableViewController'
#pod 'SwiftyJSON', '>~> 2.1.3'
pod 'SWTableViewCell', '~> 0.3.6'
pod 'IQKeyboardManager', '~> 3.3.2'

pod 'AMap3DMap', '~> 3.1.0.1'
pod 'AMapSearch', '~> 3.0.0'

pod 'AVOSCloud', '~> 3.1.4'
#pod 'FoldingTabBar', '~> 1.0.0'

pod 'HSDatePickerViewController', '~> 1.0.1'

pod 'RESideMenu', '~> 4.0.7'